# Generated by Django 5.2.14 on 2026-06-24 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0008_asset_depreciation_method_asset_residual_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Document file', upload_to='assets/attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('warranty_document', 'Warranty Document'), ('maintenance_report', 'Maintenance Report'), ('vendor_contract', 'Vendor Contract'), ('receipt', 'Receipt'), ('warranty_certificate', 'Warranty Certificate'), ('specification', 'Specification'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.asset')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='attachments.attachment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('delete', 'Delete'), ('upload', 'Upload')], max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='attachments.attachment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['asset', 'file_type'], name='attachments_asset_i_2a6c49_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['asset', 'is_current'], name='attachments_asset_i_5caa4b_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_at'], name='attachments_uploade_14f7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentaccess',
            index=models.Index(fields=['attachment', 'accessed_at'], name='attachments_attachm_e07f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentaccess',
            index=models.Index(fields=['user', 'accessed_at'], name='attachments_user_id_29a7e9_idx'),
        ),
    ]
