# Generated by Django 5.2.14 on 2026-08-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_heads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_content_82c59b_idx',
            old_name='core_auditlog_content_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_7b678c_idx',
            old_name='core_auditlog_user_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_096de0_idx',
            old_name='core_auditlog_action_idx',
        ),
    ]
