# Generated by Django 5.2.14 on 2026-06-24 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0008_asset_depreciation_method_asset_residual_value_and_more'),
        ('locations', '0003_add_city_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('planned_date', models.DateField()),
                ('audit_date', models.DateField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='Limit audit to specific asset category (optional)', max_length=32)),
                ('total_assets_audited', models.PositiveIntegerField(default=0)),
                ('assets_found', models.PositiveIntegerField(default=0)),
                ('assets_not_found', models.PositiveIntegerField(default=0)),
                ('assets_with_issues', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditors', models.ManyToManyField(help_text='Users assigned as auditors for this session', related_name='audits_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Limit audit to specific location (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
            ],
            options={
                'verbose_name': 'Audit Session',
                'verbose_name_plural': 'Audit Sessions',
                'ordering': ['-audit_date', '-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('found', 'Found'), ('not_found', 'Not Found'), ('damaged', 'Damaged'), ('condition_issue', 'Condition Issue'), ('location_mismatch', 'Location Mismatch'), ('ownership_mismatch', 'Ownership Mismatch'), ('other', 'Other')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Detailed notes about the finding')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('current_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], help_text='Condition observed during audit', max_length=20)),
                ('evidence_notes', models.TextField(blank=True, help_text='Evidence or photo descriptions')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='assets.asset')),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to=settings.AUTH_USER_MODEL)),
                ('current_location', models.ForeignKey(blank=True, help_text='Actual location found during audit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_location_findings', to='locations.location')),
                ('audit_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.auditsession')),
            ],
            options={
                'verbose_name': 'Audit Finding',
                'verbose_name_plural': 'Audit Findings',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='VarianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expected', models.PositiveIntegerField()),
                ('total_found', models.PositiveIntegerField()),
                ('total_missing', models.PositiveIntegerField()),
                ('damaged_count', models.PositiveIntegerField(default=0)),
                ('condition_issues_count', models.PositiveIntegerField(default=0)),
                ('location_mismatches_count', models.PositiveIntegerField(default=0)),
                ('ownership_mismatches_count', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of assets correctly located', max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional variance report notes')),
                ('audit_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variance_report', to='audits.auditsession')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Variance Report',
                'verbose_name_plural': 'Variance Reports',
            },
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['status', '-audit_date'], name='audits_audi_status_dd9250_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsession',
            index=models.Index(fields=['created_by', '-created_at'], name='audits_audi_created_b423f8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['audit_session', 'status'], name='audits_audi_audit_s_1d7c74_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['asset', '-verified_at'], name='audits_audi_asset_i_767ea8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditfinding',
            unique_together={('audit_session', 'asset')},
        ),
    ]
