# Generated by Django 5.2.14 on 2026-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0012_populate_audit_id_and_make_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsession',
            name='audit_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
