# Generated by Django 5.2.14 on 2026-05-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_status_0f8347_idx',
            old_name='asset_status_cat_idx',
        ),
    ]
