# Generated by Django 5.2.14 on 2026-05-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_add_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('in_use', 'In use'), ('available', 'Available'), ('ready', 'Ready'), ('maintenance', 'Under maintenance'), ('retired', 'Retired'), ('disposed', 'Disposed'), ('lost', 'Lost')], db_index=True, default='available', max_length=32),
        ),
    ]
