# Generated by Django 5.2.14 on 2026-06-19 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_assigned_to_to_fk'),
        ('locations', '0003_add_city_field'),
        ('manufacturers', '0002_seed_manufacturers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], max_length=32)),
                ('to_status', models.CharField(choices=[('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], max_length=32)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
            ],
            options={
                'verbose_name': 'Asset Status History',
                'verbose_name_plural': 'Asset Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='allocated_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('monitor', 'Monitor'), ('server', 'Server'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('network', 'Network'), ('equipment', 'Equipment'), ('other', 'Other')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase cost in company currency', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], db_index=True, default='available', max_length=32),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'location'], name='assets_asse_status_c237de_idx'),
        ),
        migrations.AddField(
            model_name='assetstatushistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
