# Generated by Django 5.2.14 on 2026-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assetstatushistory_alter_asset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('straight_line', 'Straight Line'), ('declining', 'Declining Balance'), ('units', 'Units of Production')], default='straight_line', help_text='Depreciation calculation method', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='residual_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated residual value after depreciation', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, help_text='Expected useful life in years', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('procured', 'Procured (ordered, not yet received)'), ('received', 'Received (in warehouse, not yet processed)'), ('in_stock', 'In Stock (ready for assignment)'), ('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], db_index=True, default='available', max_length=32),
        ),
        migrations.AlterField(
            model_name='assetstatushistory',
            name='from_status',
            field=models.CharField(choices=[('procured', 'Procured (ordered, not yet received)'), ('received', 'Received (in warehouse, not yet processed)'), ('in_stock', 'In Stock (ready for assignment)'), ('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='assetstatushistory',
            name='to_status',
            field=models.CharField(choices=[('procured', 'Procured (ordered, not yet received)'), ('received', 'Received (in warehouse, not yet processed)'), ('in_stock', 'In Stock (ready for assignment)'), ('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], max_length=32),
        ),
    ]
