# Generated by Django 5.2.14 on 2026-06-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_enhance_asset_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('procured', 'Procured (ordered, not yet received)'), ('received', 'Received (in warehouse, not yet processed)'), ('in_stock', 'In Stock (ready for assignment)'), ('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='assetstatushistory',
            name='to_status',
            field=models.CharField(blank=True, choices=[('procured', 'Procured (ordered, not yet received)'), ('received', 'Received (in warehouse, not yet processed)'), ('in_stock', 'In Stock (ready for assignment)'), ('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], max_length=32),
        ),
    ]
