# Generated by Django 5.2.14 on 2026-06-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_assetstatushistory_from_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific specifications (CPU, RAM, etc.)'),
        ),
    ]
