# Generated by Django 5.2.14 on 2026-05-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_status_e30b6b_idx',
            old_name='assign_status_date_idx',
        ),
    ]
