# Generated by Django 5.2.14 on 2026-06-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_assigned_to_assignment_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='user',
            new_name='assigner',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('available', 'Available'), ('assigned', 'Assigned'), ('retired', 'Retired'), ('disposed', 'Disposed'), ('lost', 'Lost'), ('damaged', 'Damaged')], db_index=True, default='active', max_length=32),
        ),
    ]
