# Generated by Django 5.2.14 on 2026-06-22 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assetstatushistory_alter_asset_options_and_more'),
        ('assignments', '0004_rename_user_to_assigner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-assigned_date', '-id'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='return_date',
            new_name='actual_return_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to_name',
            field=models.CharField(default='', help_text='Name of person asset is assigned to (if not a system user)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, help_text='System user receiving this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='condition_on_return',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], help_text='Condition of asset when returned', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], db_index=True, default='assigned', help_text='Current status of this assignment', max_length=32),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['asset', 'status'], name='assignments_asset_i_33bfc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['assigned', 'in_use'])), fields=('asset',), name='only_one_active_assignment_per_asset'),
        ),
    ]
