# Generated by Django 5.2.14 on 2026-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('procured', 'Procured (ordered, not yet received)'), ('received', 'Received (in warehouse, not yet processed)'), ('in_stock', 'In Stock (ready for assignment)'), ('ready', 'Ready (not yet assigned)'), ('available', 'Available (not assigned)'), ('assigned', 'Assigned to user'), ('in_use', 'In use by assignee'), ('maintenance', 'Under maintenance'), ('overdue', 'Return overdue'), ('returned', 'Returned (processing)'), ('found', 'Found (was lost, now recovered)'), ('retired', 'Retired from service'), ('disposed', 'Disposed'), ('lost', 'Lost/Missing'), ('damaged', 'Damaged (non-repairable)')], db_index=True, default='assigned', help_text='Current status of this assignment', max_length=32),
        ),
    ]
