# Generated by Django 5.2.14 on 2026-05-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='uniq_location_code_when_set',
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('code',), name='uniq_location_code_when_set'),
        ),
    ]
