# Generated by Django 5.2.14 on 2026-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('it_admin', 'IT Admin'), ('asset_manager', 'Asset Manager'), ('department_manager', 'Department Manager'), ('auditor', 'Auditor'), ('employee', 'Employee'), ('admin', 'Admin (Legacy)'), ('it_staff', 'IT Staff (Legacy)'), ('user', 'User (Legacy)')], db_index=True, default='employee', max_length=20),
        ),
    ]
