# Generated by Django 5.2.14 on 2026-06-22 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assetstatushistory_alter_asset_options_and_more'),
        ('licenses', '0002_remove_license_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to_name', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_assignments', to='assets.asset')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_assignments', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='licenses.softwarelicense')),
            ],
            options={
                'verbose_name': 'license assignment',
                'verbose_name_plural': 'license assignments',
                'ordering': ['-assigned_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('assigned_to_user__isnull', False), ('revoked_at__isnull', True)), fields=('license', 'assigned_to_user'), name='uniq_active_license_assignment_per_user'), models.UniqueConstraint(condition=models.Q(('asset__isnull', False), ('revoked_at__isnull', True)), fields=('license', 'asset'), name='uniq_active_license_assignment_per_asset')],
            },
        ),
    ]
