# Generated by Django on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_licenseassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwarelicense",
            name="annual_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="softwarelicense",
            name="cost_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
