# Generated by Django 5.2.14 on 2026-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_add_annual_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarelicense',
            name='active_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
